# Generated by Django 4.2.30 on 2026-06-10 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(choices=[('viz_capture', 'Visualiser Capture'), ('stream_clip', 'Stream Clip'), ('audio_extract', 'Audio Extract'), ('composed_story', 'Composed Story')], max_length=30)),
                ('file', models.FileField(upload_to='jobs/pieces/')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('output_width', models.PositiveIntegerField(default=1080)),
                ('output_height', models.PositiveIntegerField(default=1920)),
                ('output_fps', models.PositiveIntegerField(default=30)),
                ('max_duration_seconds', models.PositiveIntegerField(default=60, help_text='Max output duration (60s for Stories, 90s for Reels)')),
                ('logo_path', models.CharField(blank=True, max_length=500)),
                ('logo_position_x', models.FloatField(default=0.05, help_text='0-1 fraction from left')),
                ('logo_position_y', models.FloatField(default=0.03, help_text='0-1 fraction from top')),
                ('logo_scale', models.FloatField(default=0.15)),
                ('show_driver_name', models.BooleanField(default=True)),
                ('show_run_stats', models.BooleanField(default=True)),
                ('show_speed_overlay', models.BooleanField(default=True)),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('font_size', models.PositiveIntegerField(default=48)),
                ('font_color', models.CharField(default='white', max_length=20)),
                ('text_bg_color', models.CharField(default='rgba(0,0,0,0.6)', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StreamSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='YouTube stream or VOD URL')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ig_story', 'Instagram Story'), ('ig_reel', 'Instagram Reel'), ('yt_short', 'YouTube Short'), ('yt_video', 'YouTube Video')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('platform_url', models.URLField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_results', to='pipeline.contentpiece')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdl_run_id', models.IntegerField(db_index=True)),
                ('event_session_id', models.IntegerField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('run_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('capturing', 'Capturing Viz'), ('clipping', 'Clipping Stream'), ('composing', 'Composing Story'), ('publishing', 'Publishing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='triggered', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('failed_stage', models.CharField(blank=True, max_length=50)),
                ('run_metadata', models.JSONField(blank=True, default=dict, help_text='Snapshot of run data from rdl-base API')),
                ('skip_youtube_clip', models.BooleanField(default=False)),
                ('publish_as_reel', models.BooleanField(default=False, help_text='Publish as Reel instead of Story')),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.streamsource')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.contenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentpiece',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='pipeline.job'),
        ),
    ]
