# Generated by Django 6.0.6 on 2026-06-11 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_restructure_event_add_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdl_run_id', models.PositiveIntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('run_type', models.CharField(blank=True, max_length=50)),
                ('run_number', models.PositiveIntegerField(blank=True, null=True)),
                ('rdl_created_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pipeline.event')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pipeline.session')),
            ],
            options={
                'ordering': ['-rdl_run_id'],
            },
        ),
    ]
