# Generated by Django 6.0.6 on 2026-06-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_add_run_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status_message',
            field=models.CharField(blank=True, help_text='Live progress message for the current pipeline stage', max_length=255),
        ),
    ]
