# Generated by Django 6.0.6 on 2026-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_add_job_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ad_frequency',
            field=models.PositiveIntegerField(default=10, help_text='Publish an ad every N posts'),
        ),
        migrations.AddField(
            model_name='event',
            name='ad_instagram_handle',
            field=models.CharField(default='truedriftofficial', help_text='IG handle to tag in ad posts', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='ad_video',
            field=models.FileField(blank=True, upload_to='events/ads/'),
        ),
        migrations.AddField(
            model_name='event',
            name='ads_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='events/audio/'),
        ),
        migrations.AddField(
            model_name='event',
            name='posts_since_last_ad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
