# Generated by Django 6.0.6 on 2026-06-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_event_audio_and_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sfx_entry',
            field=models.FileField(blank=True, upload_to='events/sfx/'),
        ),
        migrations.AddField(
            model_name='event',
            name='sfx_score_totals',
            field=models.FileField(blank=True, upload_to='events/sfx/'),
        ),
        migrations.AddField(
            model_name='event',
            name='sfx_stats',
            field=models.FileField(blank=True, upload_to='events/sfx/'),
        ),
        migrations.AddField(
            model_name='event',
            name='sfx_zone',
            field=models.FileField(blank=True, upload_to='events/sfx/'),
        ),
    ]
